// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "portal-20200110232951-hostingbucket-test",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d3mo9sl8bmsfzr.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-2:76b35bfe-03d2-4671-815c-e9d0a800f946",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dbRGQxY32",
    "aws_user_pools_web_client_id": "198ivfc01ie4ackufbfb494gss",
    "oauth": {
        "domain": "shimblyportal097db43b-097db43b-test.auth.us-east-2.amazoncognito.com",
        "scope": ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
        "redirectSignIn": "http://localhost:3000",
        "redirectSignOut": "http://localhost:3000",
        "responseType": "code"
      },
      "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
